### ISSUE TITLE
"category_per_class.txt" in dataloader of shapenet dataset

### ISSUE THREAD

**Issue by Forrest-ht** [erictuanle/GoingDeeperwPointNetworks#8]
Hi, how to download the "category_per_class.txt" of shapenet dataset.
Anyone know? Thank you

**Comment by erictuanle** [comment]
Hello,
Please find below the link to download the 'category_per_class.txt' file:
https://geometry.cs.ucl.ac.uk/projects/2020/deepleanpn/training_files/category_per_class.txt
Thank you.

**Comment by Ivan-VV** [comment]
I love you！！！Because I have the same problem！
